[package]
name = "compiler-entrypoint"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "compiler-entrypoint"
path = "main.rs"

[workspace]
members = ["crates/_compiler", "crates/logger", "crates/parser", "crates/schema"]
resolver = "3"

[dependencies]
compiler = { package = "_compiler", path = "crates/_compiler" }
