[workspace]
resolver = "2"
members = [
    "cli",
    "native",
    "core/crates/api",
    "core/crates/builder",
    "core/crates/compiler",
    "core/crates/parser",
    "core/crates/ir_types",
    "core/crates/codegen",
    "core/crates/lowering",
    "core/crates/runtime",
]
exclude = ["out"]

[workspace.dependencies]
napi = { version = "3.6.1", features = ["napi4"] }
napi-derive = "3.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
napi-build = "2"
anyhow = "1"
