[workspace]
resolver = "2"
members = [
    "cli",
    "old_compiler/crates/core_api",
    "old_compiler/crates/parser",
    "old_compiler/crates/ir_types",
    "old_compiler/crates/codegen",
    "old_compiler/crates/lowering",
    "old_compiler/crates/runtime",
    "old_compiler/crates/node"
]
exclude = ["out"]

[workspace.dependencies]
napi = { version = "3.6.1", features = ["napi4"] }
napi-derive = "3.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
napi-build = "2"
