[package]
name = "ts2rust-node"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
napi = { workspace = true, features = ["napi4"] }
napi-derive = { workspace = true }
ts2rust-core = { path = "../core" }
uuid = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
